Fail the job if deploy test-cases fails

diff --git a/.github/workflows/setup-test-cluster.yaml b/.github/workflows/setup-test-cluster.yaml
--- a/.github/workflows/setup-test-cluster.yaml
+++ b/.github/workflows/setup-test-cluster.yaml
@@ -111,3 +111,7 @@ jobs:
         run: |
           chmod +x ./scripts/shell/deploy_test_scenarios.sh
           ./scripts/shell/deploy_test_scenarios.sh
+          if [ $? -ne 0 ]; then
+              echo "Failed to deploy all single-namespace test-cases"
+              exit 1
+          fi
